[package]
name = "vj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg = {version="4.2.2", package="ffmpeg-next",features = ["codec", "format"]}
