name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Linux - FFmpeg 4.2 - build, test and lint
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:4.2-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt update
          apt install -y --no-install-recommends clang curl pkg-config
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build
        run: |
          cargo build
      - name: Test
        run: |
          cargo test
      - name: Lint
        run: |
          cargo clippy -- -D warnings
      - name: Check format
        run: |
          cargo fmt -- --check
